In [1]:
import pandas as pd

# Reading Data

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

        fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   98.957239         0   28          0           0              0
1  100.028309         0   70          0          -1              0
2   98.693116         1   39          0           0              1
3  101.434123         1   14          1          -1              1
4   99.806413         0   66          1           0              1

In [4]:
df.tail()

           fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2494   99.103635         1   22          1          -1              0
2495  101.267791         1   73          1           0              0
2496  101.758005         0   28          0           0              0
2497   99.497942         1   73          1           1              0
2498  101.639914         0    2          0          -1              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2499 entries, 0 to 2498
Data columns (total 6 columns):
fever            2499 non-null float64
bodyPain         2499 non-null int64
age              2499 non-null int64
runnyNose        2499 non-null int64
diffBreath       2499 non-null int64
infectionProb    2499 non-null int64
dtypes: float64(1), int64(5)
memory usage: 117.2 KB

In [6]:
df['fever'].value_counts()

100.938833    1
100.891749    1
98.345563     1
101.994483    1
101.242500    1
101.947085    1
100.553833    1
99.524835     1
100.461505    1
101.710278    1
98.836250     1
101.992431    1
101.155596    1
100.381382    1
100.095262    1
99.621409     1
99.625221     1
101.913948    1
100.432229    1
100.035204    1
99.022151     1
98.952954     1
101.681021    1
100.591181    1
98.166730     1
98.776969     1
101.219264    1
100.920411    1
99.903981     1
98.548818     1
             ..
98.709247     1
101.510410    1
101.253349    1
98.925236     1
100.860215    1
98.434246     1
100.907420    1
101.832154    1
101.731842    1
101.198404    1
99.182839     1
101.734316    1
99.210334     1
99.736505     1
98.570277     1
100.254139    1
100.655337    1
100.612337    1
101.700722    1
98.153400     1
101.867821    1
99.200401     1
100.400994    1
101.280702    1
99.892960     1
101.028415    1
100.559907    1
100.924639    1
101.305708    1
99.753199     1
Name: fever, Length: 2499, dtype: int64

In [7]:
df['diffBreath'].value_counts()

 0    856
-1    840
 1    803
Name: diffBreath, dtype: int64

In [8]:
df.describe()

,fever,bodyPain,age,runnyNose,diffBreath,infectionProb
count,2499.000000,2499.000000,2499.000000,2499.000000,2499.000000,2499.000000
mean,100.014375,0.505402,50.244498,0.484994,-0.014806,0.512205
std,1.140386,0.500071,29.087907,0.499875,0.810868,0.499951
min,98.000555,0.000000,1.000000,0.000000,-1.000000,0.000000
25%,99.049355,0.000000,24.000000,0.000000,-1.000000,0.000000
50%,100.009925,1.000000,50.000000,0.000000,0.000000,1.000000
75%,101.001266,1.000000,76.000000,1.000000,1.000000,1.000000
max,101.999881,1.000000,100.000000,1.000000,1.000000,1.000000

# TRAIN TEST SPLITTING

In [9]:
import numpy as np

In [10]:
def data_split(data,ratio):        # takes 2 values
    np.random.seed(42)          # random values are freezed
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    
    return data.iloc[train_indices], data.iloc[test_indices]

In [11]:
np.random.permutation(7)

array([4, 6, 1, 0, 2, 3, 5])

In [12]:
train, test = data_split(df, 0.3)

In [13]:
train

           fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2121  100.140026         0   54          0          -1              1
1779   99.088087         1   47          1          -1              0
115   101.805939         0   27          1           0              1
940    99.731301         0   99          1           0              1
744    99.393802         1   62          0           0              0
1556  101.420251         1   34          0           0              1
2332  100.093046         0   20          0          -1              0
1755  101.512414         1   14          1           1              0
1582   99.786215         1   80          1          -1              1
672   101.273519         1   82          0           0              0
2305   98.695613         0   37          1           1              0
2071  100.804480         1   50          0          -1              0
2494   99.103635         1   22          1          -1              0
309    98.889726         1    1          0          -1              1
591   100.640500         1   20          0           1              1
462    98.267737         0   87          1           0              0
1461   99.784267         0   93          1          -1              0
1286   99.144039         0    5          0           1              1
1213   98.190719         0    1          0           1              0
1721  100.921583         0   77          0          -1              0
552   101.263501         1   45          1          -1              1
87     99.849688         0   27          1           1              1
690   100.172705         1    7          0           0              0
1689  101.231874         0    5          0          -1              1
2411   98.038550         0   45          0           0              0
1613  100.623512         0   30          1           0              0
1159   99.242889         1   64          1           1              1
2456   98.736995         0   28          1           0              0
1950  100.766014         0   10          0           0              1
1058   99.606936         1   18          1           1              1
...          ...       ...  ...        ...         ...            ...
1806  101.288904         1   84          0           1              1
975    99.575946         1   45          1          -1              0
2047  101.198243         1    7          0           0              1
1082  100.321520         0   94          1           1              1
474    98.191876         1   26          0           1              0
747   101.327468         1   67          0           1              0
2300   98.810491         0   48          1           1              0
21     98.077392         1   37          1           0              0
459    98.711668         0   60          1           1              1
1184   99.769742         0   93          1           1              0
2324   98.076210         1   73          0          -1              1
955    99.464799         0   50          0          -1              0
1215   98.616836         0   78          1           1              1
2433   98.026631         0   40          1          -1              0
1515  100.261156         0   75          1           1              1
2391   99.576741         1   49          0           1              1
769   101.470356         0   85          1           1              0
1685   99.060360         0   82          0           1              0
130    98.130618         0   97          1           1              0
2135   99.648131         1   84          0           0              1
1482  101.489700         1    8          0           1              0
330    98.949347         1   57          0           0              1
1238   98.052688         0   75          1          -1              0
466    99.744845         0   49          1          -1              1
2169   99.987163         1   30          0           1              1
1638   99.128175         0   72          0           0              1
1095  101.349254         1   31          1           0              0
1130  101.936666         0   22          0          -1              1
1294   99.844790         1    1          0          -1              1
860   101.062408         0   13          1           0              1

[1750 rows x 6 columns]

In [14]:
test

           fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2319  100.617850         0   46          0           1              1
1865   99.674883         1   87          0           0              1
902   100.624146         1    4          1           1              0
2240   98.042351         0   63          1           0              0
1285  100.982671         1    6          0          -1              1
56    101.386942         1    9          1          -1              0
1681  101.720471         1   35          0           0              0
802    98.000555         0   62          0           1              1
812    98.464557         0   10          1          -1              0
903    98.776204         0    9          1          -1              0
332   101.248425         0   55          1           0              1
1837   98.584509         1   35          1           1              1
2400  101.425852         1    6          1           0              0
1444  100.938638         0   77          0           0              0
2029   99.844123         1   53          1           0              0
1871  100.556085         1   36          0          -1              1
786   100.074865         0   76          1           1              0
1530   99.490462         0   31          0           0              0
485   100.227804         0   47          1           0              1
2471  101.416293         1   71          0           0              0
134   100.226464         1   79          1           0              1
1538  101.318408         1   40          0           0              0
1352  101.878255         0   78          1           1              0
1922  100.569437         1   40          0           1              1
1279  100.497107         0   43          0           1              1
246   100.335070         1   72          1           1              0
1547   99.453182         0   73          0           0              1
789   100.953831         1   81          1          -1              1
259   100.858118         0   84          0          -1              1
422    98.747819         0   42          0           1              1
...          ...       ...  ...        ...         ...            ...
2239   98.950346         1   81          1           1              0
1080   98.811658         1   29          0          -1              1
881    99.956557         1   92          0          -1              1
382   100.513473         0    6          1           1              1
1604   99.286388         0   80          0           0              1
1621  101.028415         0   13          1           1              1
727    98.515136         1    4          1          -1              0
845    99.030768         0   83          1           0              1
2436   98.433896         1    8          0          -1              1
1041   98.848661         0   34          0           0              1
263    99.454477         0   18          1           1              0
1406   99.918420         0   73          1           0              1
2158  101.563269         1   83          1           0              1
2485  101.386921         1   80          0           1              0
415    98.716930         1   32          0          -1              1
929    98.565923         0   41          0           0              1
358   100.427988         1   17          1          -1              0
1177  101.730607         0   35          0           1              0
8     100.667932         1   59          0          -1              1
1657  101.055257         1   33          0           1              0
316   101.783670         0   81          1           0              1
304    99.947483         0   27          1           1              0
427   100.467750         1   10          1           1              1
105   101.013536         1   37          1           0              0
1490   98.934585         1   82          1          -1              1
121   101.790701         1   61          0           1              0
2194  100.118588         1   38          1          -1              1
1550  100.384038         0   95          1           1              0
1901  100.898813         1   82          1           0              0
2263  101.253349         0   45          1           1              0

[749 rows x 6 columns]

In [15]:
X_train = train[['fever','bodyPain','age','runnyNose','diffBreath']].values
X_test = test[['fever','bodyPain','age','runnyNose','diffBreath']].values

In [16]:
Y_train = train[['infectionProb']].values.reshape(1750,)
Y_test = test[['infectionProb']].values.reshape(749,)

In [17]:
X_train

array([[100.1400257 ,   0.        ,  54.        ,   0.        ,
         -1.        ],
       [ 99.08808732,   1.        ,  47.        ,   1.        ,
         -1.        ],
       [101.8059387 ,   0.        ,  27.        ,   1.        ,
          0.        ],
       ...,
       [101.9366661 ,   0.        ,  22.        ,   0.        ,
         -1.        ],
       [ 99.84479043,   1.        ,   1.        ,   0.        ,
         -1.        ],
       [101.0624076 ,   0.        ,  13.        ,   1.        ,
          0.        ]])

In [18]:
Y_train

array([1, 0, 1, ..., 1, 1, 1], dtype=int64)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

C:\Users\admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
clf.predict([[100,1,22,1,1]])

array([1], dtype=int64)

In [22]:
clf.predict_proba([[100,1,22,1,1]])

array([[0.46315081, 0.53684919]])

In [23]:
inputFeatures = [102,1 ,22,-1,1]
inf_Prob = clf.predict_proba([inputFeatures])[0][1]

In [24]:
inf_Prob

0.47805338024160104